version: "3"
services:
  indigoiam:
    image: nginx:latest
    profiles:
      - iam
    environment:
      TZ: America/New_York
      NGINX_HOST: indigoiam
      NGINX_PORT: 443
    volumes:
      - $PWD/certs/ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - $PWD/certs/hostcert.pem:/etc/grid-security/hostcert.pem:z
      - $PWD/certs/hostkey.pem:/etc/grid-security/hostkey.pem:z
      - /dev/urandom:/dev/random
      - $PWD/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - indigoiam-login-service
    ports:
      - "443:443"
  iam-db:
    image: mariadb:10.11
    profiles:
      - iam
    healthcheck:
      test: mysql --user=root --password=$MARIADB_ROOT_PASSWORD -e "show databases;"
      interval: 5s
      retries: 10
    environment:
      - TZ=America/New_York
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - $PWD/dbs_and_user.sql:/docker-entrypoint-initdb.d/dbs_and_user.sql:ro
      - $PWD/data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
  indigoiam-login-service:
    image: indigoiam/iam-login-service:v1.8.3
    profiles:
      - iam
    environment:
      - IAM_JAVA_OPTS=-Djava.security.egd=file:/dev/urandom -Dspring.profiles.active=prod,oidc,registration,wlcg-scopes -agentlib:jdwp=transport=dt_socket,server=y,address=1044,suspend=n -Dlogging.file.name=/var/log/iam/iam.log
      - IAM_JWT_DEFAULT_PROFILE=wlcg
      - IAM_HOST=${IAM_HOST}
      - IAM_PORT=${IAM_PORT}
      - IAM_BASE_URL=${IAM_BASE_URL}
      - IAM_ISSUER=${IAM_ISSUER}
      - IAM_FORWARD_HEADERS_STRATEGY=native
      - IAM_KEY_STORE_LOCATION=file:/keystore.jwks
      - IAM_JWK_CACHE_LIFETIME=21600
      # - IAM_X509_TRUST_ANCHORS_DIR=/etc/grid-security/certificates
      # - IAM_X509_TRUST_ANCHORS_REFRESH=14400
      - IAM_TOMCAT_ACCESS_LOG_ENABLED=false
      - IAM_TOMCAT_ACCESS_LOG_DIRECTORY=/tmp
      - IAM_ACTUATOR_USER_USERNAME=${IAM_ACTUATOR_USER_USERNAME}
      - IAM_ACTUATOR_USER_PASSWORD=${IAM_ACTUATOR_USER_PASSWORD}
      - IAM_LOCAL_RESOURCES_ENABLE=true
      - IAM_LOCAL_RESOURCES_LOCATION=file:/indigo-iam/local-resources
      - IAM_ORGANISATION_NAME=EIC-AUTH
      - IAM_TOPBAR_TITLE="INDIGO IAM for EIC"
      - IAM_DB_HOST=iam-db
      - IAM_DB_PORT=3306
      - IAM_DB_NAME=${IAM_DB_NAME}
      - IAM_DB_USERNAME=${IAM_DB_USERNAME}
      - IAM_DB_PASSWORD=${IAM_DB_PASSWORD}
      - IAM_LOCAL_AUTHN_LOGIN_PAGE_VISIBILITY=${IAM_LOCAL_AUTHN_LOGIN_PAGE_VISIBILITY}
      - IAM_LOCAL_AUTHN_ENABLED_FOR=${IAM_LOCAL_AUTHN_ENABLED_FOR}
      - IAM_REGISTRATION_SHOW_REGISTRATION_BUTTON_IN_LOGIN_PAGE=false
      - IAM_CILOGON_CLIENT_ID=${IAM_CILOGON_CLIENT_ID}
      - IAM_CILOGON_CLIENT_SECRET=${IAM_CILOGON_CLIENT_SECRET}
      - IAM_ACCESS_TOKEN_INCLUDE_AUTHN_INFO=true
      - IAM_LOGO_URL=resources/images/jlab-logo.png
      - IAM_REGISTRATION_OIDC_ISSUER=https://cilogon.org

    volumes:
      - $PWD/keystore/iam-keystore.jwks:/keystore.jwks:ro
      - $PWD/config/application-oidc.yml:/indigo-iam/config/application-oidc.yml:ro
      - /var/log/iam/:/var/log/iam/
      - $PWD/logo/:/indigo-iam/resources/images/
    ports:
      - "127.0.0.1:8090:8090"
    depends_on:
      iam-db:
        condition: service_healthy
